### PR TITLE
Fix location tracking and remove static caching to prevent parallel test failures

### LINKED ISSUE #19: Add location tracking to Modifier and Annotation types
## Summary

Add `location: Option[Location]` fields to `Modifier` and `Annotation` case classes to enable accurate diagnostic position reporting.

## Background

Currently, `Modifier` and `Annotation` types only store their text content:

```scala
// apex-types/shared/src/main/scala/com/financialforce/types/base/Modifier.scala
case class Modifier(text: String) { ... }

// apex-types/shared/src/main/scala/com/financialforce/types/base/Annotation.scala
case class Annotation(name: String, parameters: Option[String]) { ... }
```

When consumers like apex-ls report diagnostic errors for modifiers (e.g., "protected is not supported on classes"), they have no position information and must use workarounds like offsetting from the type ID location, resulting in incorrect positions.

This affects ~32 test failures (78% of the 41 failures in apex-dev-tools/apex-ls#434).

### 1. Update Modifier class

```scala
case class Modifier(text: String, location: Option[Location] = None) {
  override def equals(obj: Any): Boolean = {
    val other = obj.asInstanceOf[Modifier]
    text.equalsIgnoreCase(other.text)
    // Note: location intentionally excluded from equality
  }

  override def hashCode(): Int = {
    text.toLowerCase.hashCode
    // Note: location intentionally excluded from hash
  }

  override def toString: String = text
}
```

### 2. Update Annotation class

```scala
case class Annotation(name: String, parameters: Option[String], location: Option[Location] = None) {
  override def equals(obj: Any): Boolean = {
    val other = obj.asInstanceOf[Annotation]
    name.equalsIgnoreCase(other.name) &&
    parameters.getOrElse("").equalsIgnoreCase(other.parameters.getOrElse(""))
    // Note: location intentionally excluded from equality
  }

  override def hashCode(): Int = {
    MurmurHash3.orderedHash(Seq(name.toLowerCase(), parameters.getOrElse("")))
    // Note: location intentionally excluded from hash
  }

  override def toString: String = {
    if (parameters.isDefined) s"@$name(${parameters.get})" else s"@$name"
  }
}
```

### 3. Update tokenToModifier to preserve locations

In `shared/src/main/scala/com/financialforce/oparser/Types.scala`:

**Current code (line 573):**
```scala
private def tokenToModifier(token: Token): Modifier = Modifier(token.contents)
```

**Updated:**
```scala
private def tokenToModifier(token: Token): Modifier =
  Modifier(token.contents, Some(token.location))
```

### 4. Update parseModifiersAndAnnotations to preserve locations

In `Types.scala` (lines 724-766):

**Current code (line 741):**
```scala
modifiers.append(tokenToModifier(tokens.get(index)))
```

**Updated approach:**
- Modifier creation already uses `tokenToModifier`, which will now preserve location (from step 3)
- For compound modifiers (e.g., "with sharing" at lines 750-752), create a spanned location:

```scala
modifiers.append(
  Modifier(
    s"${tokens.get(index).contents} ${tokens.get(index + 1).contents}",
    Some(Location.span(tokens.get(index).location, tokens.get(index + 1).location))
  )
)
```

### 5. Update parseAnnotation to preserve locations

In `Types.scala`, the `parseAnnotation` method should be updated to capture the full annotation location (from `@` through parameters).

### 6. Handle synthetic modifiers

For cases where modifiers are created without source tokens (e.g., enum constants):

**Current code (line 406):**
```scala
val field = FieldDeclaration(Array(), Array(Modifier(Tokens.StaticStr)), etd, constant)
```

**Updated (use None for synthetic modifiers):**
```scala
val field = FieldDeclaration(
  Array(),
  Array(Modifier(Tokens.StaticStr, None)),
  etd,
  constant
)
```

Or keep using `Modifier(Tokens.StaticStr)` which defaults to `None`.

### Why `Option[Location]` instead of `Location`?

1. **Backward compatibility**: Default value `None` means existing code creating `Modifier("public")` still works
2. **Synthetic modifiers**: Enum constants and other compiler-generated modifiers have no source position
3. **Graceful degradation**: Consumers can fall back to other positions if modifier location is `None`

### Why exclude location from `equals()` and `hashCode()`?

Preserves existing semantics where `Modifier("public")` equals `Modifier("public")` regardless of where they appear in source. This is important for modifier validation logic that checks for duplicates, conflicting modifiers, etc.

## Dependencies

- **Prerequisite**: #18 (Merge apex-types into outline-parser) should be completed first to make these changes in a single repo

## Testing

Existing tests in outline-parser should continue to pass since:
- `location` parameter has a default value `None`
- Location is excluded from equality checks

New tests could verify that locations are properly captured, but the main validation will happen in apex-ls tests.

## Related Issues

- #18 - Merge apex-types into outline-parser
- apex-dev-tools/apex-ls#434 - Outline parser diagnostic positions inconsistent with ANTLR parser

### PR DESCRIPTION
**Pull request by nawforce**
Fixes #19

## Summary

This PR implements proper location tracking for Modifier and Annotation types and fixes parallel test failures caused by static caching.

### Location Tracking
- Changed `lineOffset` from 1-based to 0-based indexing to match ANTLR conventions
- Made end positions exclusive (`[start, end)` half-open interval) for both columns and byte offsets
- Enabled location validation in tests by comparing ANTLR vs outline parser locations

### Caching Bug Fix
- Removed `intern()` methods and static caches from `Annotation` and `Modifier` companion objects
- Removed all `intern()` calls from factory methods in `Types.scala`
- The static caches were causing parallel test failures because `ArrayInternCache` uses equality that ignores location field, returning cached instances with wrong locations

### Test Infrastructure
- Added `syncNodeModules` task to ensure node_modules are available for ScalaJS tests
- Optimized ANTLR location extraction by skipping byte offset calculation (too expensive)
- Updated `Compare.scala` to ignore byte offsets when comparing locations
- Added `UndefOr[Token]` handling for ScalaJS where `context.stop` might be undefined

### Dependency Updates
- Upgraded apex-ls to 6.0.2 to fix lexer errors with malformed files
- Upgraded Scala.js to 1.18.2 for compatibility with apex-ls 6.0.2

## Testing

All 6,303 tests pass successfully with location tracking fully enabled.

## Related Issues

- Fixes apex-dev-tools/apex-ls#434 (Category A: Modifier/Annotation location tracking)

### CODE REVIEW

File: shared/src/main/scala/com/financialforce/oparser/Buffer.scala [hunk 1]
```diff
@@ -23,7 +23,14 @@ class Buffer(backing: String) {
...
       if (capturing) backing.substring(startCharOffset, endCharOffset + 1)
       else emptyString,
-      Location(startLine, startLineOffset, startByteOffset, endLine, endLineOffset, endByteOffset)
+      Location(
+        startLine,
+        startLineOffset,
+        startByteOffset,
+        endLine,
+        endLineOffset + 1,
+        endByteOffset + 1
```
Comment (kjonescertinia) [inline shared/src/main/scala/com/financialforce/oparser/Buffer.scala]: This looks possibly dangerous for multi-byte character handling?

File: shared/src/main/scala/com/financialforce/oparser/OutlineParser.scala [hunk 2]
```diff
@@ -152,6 +152,11 @@ final class OutlineParser[TypeDecl <: IMutableTypeDeclaration, Ctx](
               val startPosition = tokens.head.location.startPosition
               tokens.clear()
               consumeClassBody(classTypeDeclaration)
+              // Consume trailing newline to match ANTLR's inclusive behavior
```
Comment (kjonescertinia) [inline shared/src/main/scala/com/financialforce/oparser/OutlineParser.scala]: We are repeating this block a few times, a helper funcion may be better
